---
- name: add postgres apt repo
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ wheezy-pgdg main" state=present

- name: import postgres repo key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: update apt with latest postgres
  apt: update_cache=yes

- name: ensure postgres packages are installed
  apt: pkg={{ item }} state=installed
  with_items:
   - postgresql
   - libpq-dev
   - python-psycopg2

- name: ensure database is present
  postgresql_db: db={{ db_name }} encoding='UTF-8' lc_collate='en_US.utf8' lc_ctype='en_US.utf8' template='template0' state=present
  sudo: yes
  sudo_user: postgres

- name: ensure user has access to database
  postgresql_user: db={{db_name}} user={{db_user}} password={{db_pass}} priv=ALL role_attr_flags=NOSUPERUSER,NOCREATEDB
  sudo: yes
  sudo_user: postgres

- name: set listen address
  lineinfile: dest=/etc/postgresql/9.3/main/postgresql.conf state=present line="listen_addresses = '*'" insertbefore="^#listen_addresses" regexp="^listen_addresses"
  notify: restart postgres

- name: allow connections from appservers
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf owner=postgres group=postgres mode=0640
  notify: restart postgres

