---
- name: ensure app_user exists
  user: name={{app_user}} state=present

- name: install jvm
  apt: pkg=openjdk-7-jre-headless state=installed

- name: setup application conf
  template: src=templates/application.conf.j2 dest=/etc/{{app_file}}.conf 

- name: copy application to remote
  copy: src=../target/universal/{{app_name_version}}.zip dest=/tmp/{{app_name_version}}.zip force=no

- name: extract app
  command: unzip -qo /tmp/{{app_name_version}}.zip -d /tmp

- name: give app_user permission to the appdir
  file: path=/tmp/{{app_name_version}} state=directory owner={{ app_user }} group={{ app_user }} recurse=yes

- name: ensure start script is executable
  file: path=/tmp/{{app_name_version}}/bin/{{ app_file }} state=file mode=0755

  # the init.d file shouldn't be changing often, as it only depends on $app_name
- name: create init.d file
  template: src=app_initd.j2 dest=/etc/init.d/{{app_file}} owner=root group=root mode=0755
  sudo: true
  notify: update initd install

  # flush here to make sure service is installed for service tasks below
- meta: flush_handlers

- name: stop app service
  service: name={{app_file}} state=stopped

- name: clean up old deployment
  file: path=/opt/{{app_file}} state=absent

- name: ensure app folders exists
  file: path=/opt/{{app_file}} state=directory owner={{ app_user }} group={{app_user}}

- name: copy over the updated app
  shell: cp -a /tmp/{{app_name_version}}/* /opt/{{app_file}}/

- name: start app service
  service: name={{app_file}} state=started enabled=yes
